# Generated by Django 4.1.7 on 2023-04-26 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('curso', models.IntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='registroUsuario',
            new_name='registro_Usuario',
        ),
    ]
